### ISSUE TITLE
Data Wrangling - Zeitreiehen Aggregationen (Mean, Median, Max, Min)

### ISSUE THREAD

**Issue by 7ben18** [CDL1-Sensor/Sensor_Data-Wrangling-und-EDA#12]
- [x] zbsp. 5 Sekunden, aber eine Funktion indem man die Zeit als Parameter definieren kann
- [ ] Ueberlappende Fenster (Aufpassen wegen Data Leakage)
- [ ]

**Comment by Manjavy** [comment]
[[https://towardsdatascience.com/feature-engineering-on-time-series-data-transforming-signal-data-of-a-smartphone-accelerometer-for-72cbe34b8a60](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Ftowardsdatascience.com%2Ffeature-engineering-on-time-series-data-transforming-signal-data-of-a-smartphone-accelerometer-for-72cbe34b8a60&data=05%7C01%7Cmanjavy.kirupa%40students.fhnw.ch%7Ca58a6576429344a6e69708db2f6ca714%7C9d1a5fc8321e4101ae63530730711ac2%7C0%7C0%7C638155915920124134%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=OqOpheVPO6I0cv8x81P5fxpPvDAANzdbD7REK1JkBUQ%3D&reserved=0)](https://towardsdatascience.com/feature-engineering-on-time-series-data-transforming-signal-data-of-a-smartphone-accelerometer-for-72cbe34b8a60)

**Comment by 7ben18** [comment]
created function for aggregation timeseries data. 
branch: data-aggregation

**Comment by 7ben18** [comment]
ueberlappe fenster evtl neues issue
